permalink: /:categories/:year/:month/:day/:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: "pygments"
markdown: rdiscount

# Themes are encouraged to use these universal variable
# so be sure to set them if your theme uses them.
title : GHTorrent
tagline: Query Github data!
author :
  name : Georgios Gousios
  email : georgios@cs.ru.nl
  github : gousiosg
  twitter : gousiosg
  feedburner :

production_url : http://www.ghtorrent.org

JB :
  version : 0.2.13
  BASE_PATH : false
  ASSET_PATH : false
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  comments :
    provider : disqus
    disqus :
      short_name : ghtorrent
    livefyre :
      site_id : 123
    intensedebate :
      account : 123abc
    facebook :
      appid : 123
      num_posts: 5
      width: 580
      colorscheme: light
  analytics :
    provider : google
    google :
        tracking_id : 'UA-38537159-1'
    getclicky :
      site_id :
    mixpanel :
        token : '_MIXPANEL_TOKEN_'
  sharing :
    provider : addthis

scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending

  source: ./_bibliography
  bibliography: references
  bibliography_template: "{{reference}}"

  replace_strings: true

  details_dir:    bibliography
  details_layout: bib_details.html
  details_link:   more...

  query: "@*"

